In [ ]:
#importing libraries
import pandas as pd
import random

In [ ]:
number_candidates = 50

In [ ]:
candidates=[]

In [ ]:
#Generating random candidate data using the random library
for i in range(number_candidates): 
  gender= random.choice(["M", "F"])
  age=  random.randint(18,50)
  years_of_experience= random.randint(0,15)
  skill_score=random.random()
  work_ethic=random.random()
  attitude_score=random.random()
  ethnicity= random.choice(["Black", "White", "Asian", "Arab", "Other"])
  disability=random.choice([0,1])
  legal_history=random.choice([0,1])
  country_of_origin=random.randint(0,217)
  time_spent_viewing=random.randint(3,120)
  hired =random.choice([0,1])
  candidates.append([gender, age, years_of_experience, skill_score, work_ethic, attitude_score,ethnicity, disability, legal_history, country_of_origin, time_spent_viewing, hired])

In [ ]:
candidates

[['F',
  21,
  9,
  0.9988273525796895,
  0.26463902030700803,
  0.6339745208429021,
  'White',
  1,
  0,
  165,
  118,
  0],
 ['F',
  45,
  1,
  0.08613105543296473,
  0.4147632376213787,
  0.010336269079479377,
  'White',
  0,
  0,
  101,
  33,
  0],
 ['F',
  42,
  1,
  0.6130426734242282,
  0.24902991059128454,
  0.08015581079535539,
  'Black',
  1,
  0,
  31,
  117,
  1],
 ['F',
  21,
  3,
  0.8474415423414089,
  0.6527707421868463,
  0.9651278008762944,
  'Black',
  1,
  0,
  94,
  79,
  1],
 ['M',
  25,
  4,
  0.25732368692439334,
  0.7896551273130454,
  0.08279536742055682,
  'Arab',
  0,
  1,
  178,
  47,
  0],
 ['F',
  49,
  9,
  0.8344076739299295,
  0.041453367377758954,
  0.038029327016861125,
  'Asian',
  1,
  1,
  3,
  109,
  0],
 ['F',
  20,
  7,
  0.8597082369447461,
  0.7486446783142531,
  0.37764405885565366,
  'Other',
  0,
  1,
  209,
  103,
  0],
 ['F',
  26,
  10,
  0.8981498866056002,
  0.4919759811207086,
  0.9512638558753319,
  'Other',
  0,
  1,
  149,
  15,
  1],
 ['M',
  21,
  3,
  0.18929893506623963,
  0.4592637796323952,
  0.734771949185897,
  'Black',
  1,
  0,
  100,
  17,
  1],
 ['M',
  31,
  3,
  0.832429512794989,
  0.24246081350845738,
  0.9547380451605725,
  'Asian',
  1,
  1,
  204,
  75,
  1],
 ['M',
  44,
  6,
  0.10256656946286458,
  0.49729146813420066,
  0.31324350165113024,
  'White',
  0,
  1,
  134,
  105,
  1],
 ['F',
  25,
  1,
  0.6174383516286558,
  0.19227543550902004,
  0.7643651021151959,
  'Asian',
  1,
  1,
  39,
  52,
  1],
 ['M',
  42,
  13,
  0.1741347299310071,
  0.13306243514820337,
  0.09095836693775661,
  'Arab',
  0,
  1,
  31,
  61,
  1],
 ['M',
  33,
  11,
  0.13209848524439938,
  0.8283002263346967,
  0.0928955186185173,
  'Other',
  0,
  0,
  19,
  47,
  0],
 ['F',
  19,
  15,
  0.9283910975821321,
  0.9137894075196421,
  0.27972116902166666,
  'Arab',
  0,
  0,
  63,
  110,
  1],
 ['M',
  44,
  8,
  0.2927728034074698,
  0.9856224396719884,
  0.08673863890330291,
  'Asian',
  0,
  1,
  195,
  82,
  0],
 ['M',
  50,
  2,
  0.2692191829458852,
  0.803012838892041,
  0.38822205369083485,
  'Asian',
  0,
  1,
  164,
  114,
  1],
 ['F',
  48,
  14,
  0.6256089498819557,
  0.6012109429426409,
  0.8287881636929296,
  'White',
  0,
  1,
  110,
  46,
  0],
 ['M',
  43,
  9,
  0.49747357423327,
  0.14249080206677633,
  0.7079392735781154,
  'Black',
  1,
  0,
  189,
  71,
  0],
 ['F',
  40,
  15,
  0.9652728084477874,
  0.3139162451978992,
  0.17082820193410808,
  'Arab',
  1,
  0,
  36,
  12,
  0],
 ['F',
  36,
  2,
  0.47788649800297445,
  0.4869056072289367,
  0.4319865599934175,
  'White',
  0,
  1,
  37,
  77,
  0],
 ['F',
  35,
  10,
  0.6547988339301307,
  0.970958056952953,
  0.8100016553581127,
  'Other',
  1,
  0,
  180,
  21,
  1],
 ['F',
  47,
  1,
  0.1791682583210601,
  0.29639998074940577,
  0.5659060848814185,
  'White',
  1,
  1,
  41,
  116,
  1],
 ['M',
  44,
  12,
  0.413393893189567,
  0.5392081765003258,
  0.866010862857819,
  'Arab',
  0,
  1,
  4,
  9,
  0],
 ['M',
  28,
  15,
  0.2890267534812625,
  0.8205876908594891,
  0.48674465903324404,
  'Black',
  1,
  0,
  73,
  33,
  1],
 ['M',
  27,
  8,
  0.943216708560033,
  0.6506440150454006,
  0.21814855717302162,
  'Black',
  1,
  1,
  31,
  100,
  0],
 ['M',
  42,
  9,
  0.40248434856959836,
  0.9920501098727217,
  0.9675020339649416,
  'Arab',
  1,
  1,
  180,
  28,
  1],
 ['F',
  39,
  8,
  0.5419593100979752,
  0.17113284916243487,
  0.42111519133975583,
  'Black',
  1,
  0,
  115,
  113,
  1],
 ['M',
  18,
  4,
  0.6144260013728867,
  0.6599369968667405,
  0.8671407745863631,
  'White',
  1,
  0,
  149,
  103,
  1],
 ['F',
  30,
  10,
  0.1714482767976464,
  0.006757870148234146,
  0.9815376166538311,
  'Other',
  1,
  0,
  37,
  95,
  0],
 ['F',
  26,
  4,
  0.37335089198808324,
  0.1238284052815316,
  0.4886679421268264,
  'Black',
  0,
  1,
  130,
  73,
  1],
 ['F',
  37,
  5,
  0.4939223068602312,
  0.6543530908018222,
  0.9473231616772688,
  'White',
  0,
  1,
  215,
  82,
  0],
 ['F',
  45,
  3,
  0.2217468943584433,
  0.6247168352023192,
  0.43383872745219565,
  'Black',
  1,
  1,
  94,
  99,
  0],
 ['M',
  42,
  1,
  0.9328101342664966,
  0.5834364481426498,
  0.3335952512277476,
  'White',
  1,
  0,
  94,
  65,
  1],
 ['M',
  18,
  11,
  0.34000081621897693,
  0.4298552131390747,
  0.7357789487314972,
  'White',
  1,
  1,
  174,
  35,
  0],
 ['F',
  37,
  9,
  0.8060733968414684,
  0.9392420496456323,
  0.8204198647395505,
  'Black',
  1,
  0,
  155,
  86,
  0],
 ['F',
  18,
  2,
  0.2082193835107652,
  0.4027826209097869,
  0.23832102475292127,
  'Other',
  0,
  0,
  191,
  62,
  1],
 ['M',
  21,
  5,
  0.4757334167895697,
  0.8904259879778925,
  0.48821893635082403,
  'Asian',
  1,
  0,
  109,
  43,
  1],
 ['M',
  28,
  5,
  0.11608900858510662,
  0.8242720710552165,
  0.19699725526281409,
  'Other',
  1,
  1,
  30,
  51,
  0],
 ['F',
  19,
  8,
  0.6681267246837018,
  0.2742157619833514,
  0.16744470897561936,
  'Asian',
  1,
  0,
  50,
  98,
  0],
 ['M',
  36,
  8,
  0.27633161134694884,
  0.8625465950297153,
  0.02696647823531384,
  'Black',
  1,
  0,
  127,
  5,
  1],
 ['M',
  35,
  9,
  0.2538969771054338,
  0.6689460608052077,
  0.9445452932551716,
  'White',
  0,
  0,
  21,
  60,
  0],
 ['M',
  19,
  9,
  0.04092410209872388,
  0.5117636423352171,
  0.17413024835383806,
  'Black',
  1,
  1,
  113,
  20,
  0],
 ['F',
  30,
  6,
  0.9995063803265462,
  0.3938180778978939,
  0.7400389137975781,
  'Black',
  0,
  1,
  149,
  7,
  0],
 ['F',
  41,
  11,
  0.7966208243955131,
  0.5748047064907417,
  0.5885987302670596,
  'Other',
  1,
  0,
  177,
  67,
  0],
 ['M',
  43,
  0,
  0.8461110342768722,
  0.2751756409361794,
  0.24195326234489778,
  'Black',
  1,
  1,
  174,
  43,
  1],
 ['M',
  26,
  11,
  0.7763364784083169,
  0.524786663370863,
  0.8330772561565499,
  'White',
  1,
  0,
  81,
  40,
  0],
 ['M',
  43,
  2,
  0.7611237863712216,
  0.31820415761576426,
  0.8575917668756512,
  'Arab',
  0,
  1,
  3,
  4,
  1],
 ['M',
  43,
  0,
  0.5720951835636194,
  0.25960655405893773,
  0.4376603665127954,
  'Arab',
  0,
  0,
  187,
  49,
  1],
 ['M',
  31,
  11,
  0.7704733598945898,
  0.5744226608203048,
  0.35935654825962815,
  'White',
  0,
  0,
  54,
  59,
  1]]

In [ ]:
#Converting the candidates matrix to a dataframe
candidates_df = pd.DataFrame(candidates, columns=['gender','age', 'years_of_experience','skill_score', 'work_ethic','attitude_score', 'ethnicity', 'disability', 'legal_history','country_of_origin', 'time_spent_viewing', 'hired' ])

In [ ]:
candidates_df

,gender,age,years_of_experience,skill_score,work_ethic,attitude_score,ethnicity,disability,legal_history,country_of_origin,time_spent_viewing,hired
0,F,21,9,0.998827,0.264639,0.633975,White,1,0,165,118,0
1,F,45,1,0.086131,0.414763,0.010336,White,0,0,101,33,0
2,F,42,1,0.613043,0.249030,0.080156,Black,1,0,31,117,1
3,F,21,3,0.847442,0.652771,0.965128,Black,1,0,94,79,1
4,M,25,4,0.257324,0.789655,0.082795,Arab,0,1,178,47,0
5,F,49,9,0.834408,0.041453,0.038029,Asian,1,1,3,109,0
6,F,20,7,0.859708,0.748645,0.377644,Other,0,1,209,103,0
7,F,26,10,0.898150,0.491976,0.951264,Other,0,1,149,15,1
8,M,21,3,0.189299,0.459264,0.734772,Black,1,0,100,17,1
9,M,31,3,0.832430,0.242461,0.954738,Asian,1,1,204,75,1
10,M,44,6,0.102567,0.497291,0.313244,White,0,1,134,105,1
11,F,25,1,0.617438,0.192275,0.764365,Asian,1,1,39,52,1
12,M,42,13,0.174135,0.133062,0.090958,Arab,0,1,31,61,1
13,M,33,11,0.132098,0.828300,0.092896,Other,0,0,19,47,0
14,F,19,15,0.928391,0.913789,0.279721,Arab,0,0,63,110,1
15,M,44,8,0.292773,0.985622,0.086739,Asian,0,1,195,82,0
16,M,50,2,0.269219,0.803013,0.388222,Asian,0,1,164,114,1
17,F,48,14,0.625609,0.601211,0.828788,White,0,1,110,46,0
18,M,43,9,0.497474,0.142491,0.707939,Black,1,0,189,71,0
19,F,40,15,0.965273,0.313916,0.170828,Arab,1,0,36,12,0
20,F,36,2,0.477886,0.486906,0.431987,White,0,1,37,77,0
21,F,35,10,0.654799,0.970958,0.810002,Other,1,0,180,21,1
22,F,47,1,0.179168,0.296400,0.565906,White,1,1,41,116,1
23,M,44,12,0.413394,0.539208,0.866011,Arab,0,1,4,9,0
24,M,28,15,0.289027,0.820588,0.486745,Black,1,0,73,33,1
25,M,27,8,0.943217,0.650644,0.218149,Black,1,1,31,100,0
26,M,42,9,0.402484,0.992050,0.967502,Arab,1,1,180,28,1
27,F,39,8,0.541959,0.171133,0.421115,Black,1,0,115,113,1
28,M,18,4,0.614426,0.659937,0.867141,White,1,0,149,103,1
29,F,30,10,0.171448,0.006758,0.981538,Other,1,0,37,95,0
30,F,26,4,0.373351,0.123828,0.488668,Black,0,1,130,73,1
31,F,37,5,0.493922,0.654353,0.947323,White,0,1,215,82,0
32,F,45,3,0.221747,0.624717,0.433839,Black,1,1,94,99,0
33,M,42,1,0.932810,0.583436,0.333595,White,1,0,94,65,1
34,M,18,11,0.340001,0.429855,0.735779,White,1,1,174,35,0
35,F,37,9,0.806073,0.939242,0.820420,Black,1,0,155,86,0
36,F,18,2,0.208219,0.402783,0.238321,Other,0,0,191,62,1
37,M,21,5,0.475733,0.890426,0.488219,Asian,1,0,109,43,1
38,M,28,5,0.116089,0.824272,0.196997,Other,1,1,30,51,0
39,F,19,8,0.668127,0.274216,0.167445,Asian,1,0,50,98,0
40,M,36,8,0.276332,0.862547,0.026966,Black,1,0,127,5,1
41,M,35,9,0.253897,0.668946,0.944545,White,0,0,21,60,0
42,M,19,9,0.040924,0.511764,0.174130,Black,1,1,113,20,0
43,F,30,6,0.999506,0.393818,0.740039,Black,0,1,149,7,0
44,F,41,11,0.796621,0.574805,0.588599,Other,1,0,177,67,0
45,M,43,0,0.846111,0.275176,0.241953,Black,1,1,174,43,1
46,M,26,11,0.776336,0.524787,0.833077,White,1,0,81,40,0
47,M,43,2,0.761124,0.318204,0.857592,Arab,0,1,3,4,1
48,M,43,0,0.572095,0.259607,0.437660,Arab,0,0,187,49,1
49,M,31,11,0.770473,0.574423,0.359357,White,0,0,54,59,1

In [ ]:
#Encoding categorical variables
gender_mapper = {"M":1, "F":0}
ethnicity_mapper = {"Black":0, "White":1, "Arab":2, "Asian":3, "Other":4}

candidates_df["gender"] = candidates_df["gender"].replace(gender_mapper)
candidates_df["ethnicity"] = candidates_df["ethnicity"].replace(ethnicity_mapper)

In [ ]:
candidates_df

,gender,age,years_of_experience,skill_score,work_ethic,attitude_score,ethnicity,disability,legal_history,country_of_origin,time_spent_viewing,hired
0,0,21,9,0.998827,0.264639,0.633975,1,1,0,165,118,0
1,0,45,1,0.086131,0.414763,0.010336,1,0,0,101,33,0
2,0,42,1,0.613043,0.249030,0.080156,0,1,0,31,117,1
3,0,21,3,0.847442,0.652771,0.965128,0,1,0,94,79,1
4,1,25,4,0.257324,0.789655,0.082795,2,0,1,178,47,0
5,0,49,9,0.834408,0.041453,0.038029,3,1,1,3,109,0
6,0,20,7,0.859708,0.748645,0.377644,4,0,1,209,103,0
7,0,26,10,0.898150,0.491976,0.951264,4,0,1,149,15,1
8,1,21,3,0.189299,0.459264,0.734772,0,1,0,100,17,1
9,1,31,3,0.832430,0.242461,0.954738,3,1,1,204,75,1
10,1,44,6,0.102567,0.497291,0.313244,1,0,1,134,105,1
11,0,25,1,0.617438,0.192275,0.764365,3,1,1,39,52,1
12,1,42,13,0.174135,0.133062,0.090958,2,0,1,31,61,1
13,1,33,11,0.132098,0.828300,0.092896,4,0,0,19,47,0
14,0,19,15,0.928391,0.913789,0.279721,2,0,0,63,110,1
15,1,44,8,0.292773,0.985622,0.086739,3,0,1,195,82,0
16,1,50,2,0.269219,0.803013,0.388222,3,0,1,164,114,1
17,0,48,14,0.625609,0.601211,0.828788,1,0,1,110,46,0
18,1,43,9,0.497474,0.142491,0.707939,0,1,0,189,71,0
19,0,40,15,0.965273,0.313916,0.170828,2,1,0,36,12,0
20,0,36,2,0.477886,0.486906,0.431987,1,0,1,37,77,0
21,0,35,10,0.654799,0.970958,0.810002,4,1,0,180,21,1
22,0,47,1,0.179168,0.296400,0.565906,1,1,1,41,116,1
23,1,44,12,0.413394,0.539208,0.866011,2,0,1,4,9,0
24,1,28,15,0.289027,0.820588,0.486745,0,1,0,73,33,1
25,1,27,8,0.943217,0.650644,0.218149,0,1,1,31,100,0
26,1,42,9,0.402484,0.992050,0.967502,2,1,1,180,28,1
27,0,39,8,0.541959,0.171133,0.421115,0,1,0,115,113,1
28,1,18,4,0.614426,0.659937,0.867141,1,1,0,149,103,1
29,0,30,10,0.171448,0.006758,0.981538,4,1,0,37,95,0
30,0,26,4,0.373351,0.123828,0.488668,0,0,1,130,73,1
31,0,37,5,0.493922,0.654353,0.947323,1,0,1,215,82,0
32,0,45,3,0.221747,0.624717,0.433839,0,1,1,94,99,0
33,1,42,1,0.932810,0.583436,0.333595,1,1,0,94,65,1
34,1,18,11,0.340001,0.429855,0.735779,1,1,1,174,35,0
35,0,37,9,0.806073,0.939242,0.820420,0,1,0,155,86,0
36,0,18,2,0.208219,0.402783,0.238321,4,0,0,191,62,1
37,1,21,5,0.475733,0.890426,0.488219,3,1,0,109,43,1
38,1,28,5,0.116089,0.824272,0.196997,4,1,1,30,51,0
39,0,19,8,0.668127,0.274216,0.167445,3,1,0,50,98,0
40,1,36,8,0.276332,0.862547,0.026966,0,1,0,127,5,1
41,1,35,9,0.253897,0.668946,0.944545,1,0,0,21,60,0
42,1,19,9,0.040924,0.511764,0.174130,0,1,1,113,20,0
43,0,30,6,0.999506,0.393818,0.740039,0,0,1,149,7,0
44,0,41,11,0.796621,0.574805,0.588599,4,1,0,177,67,0
45,1,43,0,0.846111,0.275176,0.241953,0,1,1,174,43,1
46,1,26,11,0.776336,0.524787,0.833077,1,1,0,81,40,0
47,1,43,2,0.761124,0.318204,0.857592,2,0,1,3,4,1
48,1,43,0,0.572095,0.259607,0.437660,2,0,0,187,49,1
49,1,31,11,0.770473,0.574423,0.359357,1,0,0,54,59,1

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
#A simple model for prototyping
lr = LogisticRegression(max_iter=1000)

In [ ]:
#Splitting the candidates data to input and target features
columns = ['gender','age', 'years_of_experience','skill_score', 'work_ethic','attitude_score', 'ethnicity', 'disability', 'legal_history','country_of_origin', 'time_spent_viewing']
X = candidates_df[columns]
y = candidates_df['hired']

In [ ]:
#Fitting the model
lr.fit(X,y)

LogisticRegression(max_iter=1000)

In [ ]:
#Determining feature importance by printing coefficients
lr.coef_

array([[ 0.60867994, -0.0022623 , -0.18696722,  0.29057098, -0.04224668,
         0.2998668 ,  0.01037774, -0.0045243 , -0.62918913,  0.0006638 ,
        -0.00252656]])